---

- name: Get the binary file of Ignite
  get_url:
    url: "https://github.com/weaveworks/ignite/releases/download/{{ IGNITE_VERSION }}/ignite-{{ IGNITE_ARCH }}"
    dest: "/usr/local/bin/ignite"
    owner: root
    group: root
    mode: 0755
