---

- hosts: all
  roles:
    - { role: initial.role, tags: initial }
    - { role: credentials.role, tags: credentials-admins }
    - { role: docker.role, tags: docker-install }
    - { role: ignite.role, tags: ignite-install }
    - { role: footloose.role, tags: footloose-install }
    - { role: mysql.role, tags: mysql-install }

  post_tasks:

    - name: Copy docker
      block:

        - name: Creates site directory
          file:
            path: "{{ item }}"
            state: directory
            recurse: yes
          loop: "{{ createfolder_list }}"
          when:
            - createfolder_list is defined
            - createfolder_list is iterable
            - createfolder_list | length > 0

        - name: Synchronize site directories
          synchronize:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
          loop: "{{ syncsite_list }}"
          when:
            - syncsite_list is defined
            - syncsite_list is iterable
            - syncsite_list | length > 0

        - name: Fix permissions to the syncsite_list
          file:
            path: "{{ item.dest }}/{{ item.name }}"
            owner: "{{ item.owner }}"
            group: "{{ item.group }}"
            mode: "{{ item.mode }}"
            recurse: yes
          loop: "{{ syncsite_list }}"
          when:
            - syncsite_list is defined
            - syncsite_list is iterable
            - syncsite_list | length > 0

      tags:
        - site-copy

    - name: Install specified python requirements
      pip:
        requirements: '/usr/lib/footloose-vpc/grid/requirements.txt'
      tags: python-packages-install

    - name: start site
      shell: "cd /usr/lib/footloose-vpc/grid; export FLASK_APP=main.py; flask run -h 0.0.0.0 -p 5555 &"
      tags:
        - site-start