---

- hosts: all
  roles:
    - { role: initial.role, tags: initial }
    - { role: credentials.role, tags: credentials-admins }
    - { role: docker.role, tags: docker-install }
    - { role: ignite.role, tags: ignite-install }
    - { role: footloose.role, tags: footloose-install }
    - { role: mysql.role, tags: mysql }
    - { role: nginx.role, tags: nginx }

  post_tasks:

    - name: Copy /web files
      block:

        - name: Del dirs if exist
          file:
            state: absent
            path: "{{ item }}"
          loop:
            - "/etc/footloose-vpc"
            - "/usr/lib/footloose-vpc"

        - name: Creates directories
          file:
            path: "{{ item }}"
            state: directory
            recurse: yes
          loop:
            - "/etc/footloose-vpc/"
            - "/usr/lib/footloose-vpc"

        - name: Create footloose.conf
          template:
            src: templates/footloose-vpc.conf.j2
            dest: /etc/footloose-vpc/footloose-vpc.conf
            owner: root
            group: root
            mode: 0644

        - name: Create supervisor conf for fcgiwrap
          template:
            src: templates/supervisor-fcgiwrap.conf.j2
            dest: /etc/supervisor/conf.d/fcgiwrap.conf
            owner: root
            group: root
            mode: 0644

        - name: Restarte supervisor service
          systemd:
            name: supervisor
            state: restarted

        - name: Creates directories inside /usr/lib/footloose-vpc
          file:
            path: "/usr/lib/footloose-vpc/{{ item }}"
            state: directory
            owner: "www-data"
            group: "www-data"
            recurse: yes
          loop:
            - logs

        - name: Synchronize web directories
          synchronize:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
          loop:
            - src: "../../web/static"
              dest: "/usr/lib/footloose-vpc/"
            - src: "../../web/cgi-bin"
              dest: "/usr/lib/footloose-vpc/"
            - src: "../../web/config"
              dest: "/usr/lib/footloose-vpc/"
            - src: "../../web/modules"
              dest: "/usr/lib/footloose-vpc/"

        - name: Fix permissions to the web directories (Task - 'Synchronize web directories')
          file:
            path: "{{ item.name }}"
            owner: "www-data"
            group: "www-data"
            mode: "{{ item.mode }}"
            recurse: yes
          loop:
            - name: /usr/lib/footloose-vpc/static
              mode: 'u=rwX,g=rX,o=rX'
            - name: /usr/lib/footloose-vpc/cgi-bin
              mode: 'u=rwx,g=rx,o=rx'
            - name: /usr/lib/footloose-vpc/config
              mode: 'u=rwX,g=rX,o=rX'
            - name: /usr/lib/footloose-vpc/modules
              mode: 'u=rwX,g=rX,o=rX'

        - name: Restarte nginx service
          systemd:
            name: nginx
            state: restarted

      tags:
        - web-config
