---

- hosts: all
  roles:
    - { role: initial.role, tags: initial }
    - { role: credentials.role, tags: credentials-admins }
    - { role: docker.role, tags: docker-install }
    - { role: ignite.role, tags: ignite-install }
    - { role: footloose.role, tags: footloose-install }

  post_tasks:

    - name: Copy docker
      block:

        - name: Creates directory
          file:
            path: "{{ item }}"
            state: directory
            recurse: yes
          loop: "{{ createfolder_list }}"
          when:
            - createfolder_list is defined
            - createfolder_list is iterable
            - createfolder_list | length > 0

        - name: Copy files (docker-compose)
          copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
          loop: "{{ copydocker_list }}"
          when:
            - copydocker_list is defined
            - copydocker_list is iterable
            - copydocker_list | length > 0

      tags:
        - docker-copy

    - name: start docker-compose
      shell: "cd /opt/docker; docker-compose up -d"

      tags:
        - docker-start